# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-26 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20191025_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view_grade',
            field=models.IntegerField(null=True),
        ),
    ]
